version: '3.3'
services:
  tools:
    image: scalaspark-fun-tools
    build:
      context: .
      dockerfile: Dockerfile-tools
    environment:
      - USER
    volumes:
      - "${PWD}/tools:/opt/tools"
      - "/etc/passwd:/etc/passwd"
      - "/etc/group:/etc/group"
  test:
    image: scalaspark-fun-test
    build:
      context: .
      dockerfile: Dockerfile-test
    working_dir: ${PWD}
    volumes:
      - "${PWD}/src:${PWD}/src"
      - "${PWD}/build.sbt:${PWD}/build.sbt"
    depends_on:
      - tools
